name: Build Android

on: push

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-20.04
    steps:
      # Checkout source code
      - name: Checkout source
        uses: actions/checkout@v3

      # Setup Java 17
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # Generate Android keystore dynamically
      - name: Generate Keystore
        env:
          KEYSTORE_PASSWORD: "password123"
          KEY_ALIAS: "release-key"
        run: |
          keytool -genkeypair -v \
            -keystore android.keystore \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias $KEY_ALIAS \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEYSTORE_PASSWORD \
            -dname "CN=Your Name, OU=Your Unit, O=Your Organization, L=Your City, ST=Your State, C=Your Country"

      # Install Cordova
      - name: Install Cordova
        run: npm install -g cordova

      # Add Cordova Android platform
      - name: Add Cordova Android platform
        run: cordova platform add android@12.0.0

      # Build Android release APK
      - name: Build Android release APK
        env:
          KEYSTORE_PASSWORD: "password123"
          KEY_ALIAS: "release-key"
        run: cordova build android --release -- \
          --keystore=android.keystore \
          --storePassword=$KEYSTORE_PASSWORD \
          --alias=$KEY_ALIAS \
          --password=$KEYSTORE_PASSWORD \
          --packageType=apk

      # Upload Android release APK
      - name: Upload Android release APK
        uses: actions/upload-artifact@v3
        with:
          name: android-app-release
          path: platforms/android/app/build/outputs/apk/release/app-release.apk

      # Build Android App Bundle
      - name: Build Android App Bundle
        env:
          KEYSTORE_PASSWORD: "password123"
          KEY_ALIAS: "release-key"
        run: cordova build android --release -- \
          --keystore=android.keystore \
          --storePassword=$KEYSTORE_PASSWORD \
          --alias=$KEY_ALIAS \
          --password=$KEYSTORE_PASSWORD \
          --packageType=bundle

      # Upload Android App Bundle
      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: android-app-release
          path: platforms/android/app/build/outputs/bundle/release/app-release.aab